package main

import (
	"encoding/json"
	"log"
	"net/http"
	"time"
)

const address = ":8080"

type projetoKorpResponse struct {
	Nome    string `json:"nome"`
	Horario string `json:"horario"`
}

type healthResponse struct {
	Status string `json:"status"`
}

func newHandler() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /projeto-korp", projetoKorpHandler)
	mux.HandleFunc("GET /healthz", healthHandler)
	mux.Handle("GET /metrics", metricsHandler())

	// Wrap the mux so responses generated by it, such as 404 and 405, are observed too.
	return observeHTTP(mux)
}

func projetoKorpHandler(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "application/json")

	response := projetoKorpResponse{
		Nome:    "Projeto Korp",
		Horario: time.Now().UTC().Format(time.RFC3339),
	}

	if err := json.NewEncoder(w).Encode(response); err != nil {
		log.Printf("failed to encode response: %v", err)
	}
}

func healthHandler(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "application/json")

	if err := json.NewEncoder(w).Encode(healthResponse{Status: "ok"}); err != nil {
		log.Printf("failed to encode health response: %v", err)
	}
}

func main() {
	server := &http.Server{
		Addr:              address,
		Handler:           newHandler(),
		ReadHeaderTimeout: 5 * time.Second,
	}

	log.Printf("http-server-projeto-korp listening on %s", address)

	if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
		log.Fatalf("server failed: %v", err)
	}
}
