services:
  http-server-projeto-korp:
    image: http-server-projeto-korp:local
    build:
      context: ./app
      dockerfile: Dockerfile
      target: runtime
    restart: unless-stopped
    networks:
      - korp-network

  nginx:
    image: nginx:1.30.4-trixie
    restart: unless-stopped
    depends_on:
      - http-server-projeto-korp
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - korp-network

  prometheus:
    image: prom/prometheus:v3.14.0
    restart: unless-stopped
    depends_on:
      - http-server-projeto-korp
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - korp-network

networks:
  korp-network:
    name: korp-network

volumes:
  prometheus-data: